Wecamp\Bundle\PlusplusBundle\Entity\PlusOne:
    type: entity
    table: plus_one
    repositoryClass: Wecamp\Bundle\PlusplusBundle\Entity\PlusOneRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    manyToOne:
        subject:
            targetEntity: Subject
            inversedBy: plus_ones
            joinColumn:
                name: subject_id
                referencedColumnName: id
                nullable: false

    fields:
        latitude:
            type: decimal
            nullable: true
        longitude:
            type: decimal
            nullable: true
        created:
            type: datetime
    lifecycleCallbacks: {  }
