Wecamp\Bundle\PlusplusBundle\Entity\Subject:
    type: entity
    table: subject
    repositoryClass: Wecamp\Bundle\PlusplusBundle\Entity\SubjectRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    oneToMany:
        plus_ones:
            targetEntity: PlusOne
            mappedBy: subject
    fields:
        name:
            type: string
            length: 255
    lifecycleCallbacks: {  }
