wecamp_plusplus_homepage:
    path:     /hello/{name}
    defaults: { _controller: WecampPlusplusBundle:Default:index }

list:
    path:     /
    defaults: { _controller: WecampPlusplusBundle:List:list }

_add:
    path:     /subject/add
    defaults: { _controller: WecampPlusplusBundle:Subject:add }

_createSubject:
    path:        /subject/create
    defaults:       { _controller: WecampPlusplusBundle:Subject:create }
    methods:  [POST]

_plusOneSubject:
  path: /plusone/{id}
  defaults: { _controller: WecampPlusplusBundle:Subject:plusone }
  requirements:
    id: \d+

_download:
    pattern:        /download
    defaults:       { _controller: WecampPlusplusBundle:Download:download }
    methods:        [ GET ]