
list:
    path:           /
    defaults:       { _controller: WecampPlusplusBundle:List:list }
    methods:        [ GET ]

_add:
    path:           /subject/add
    defaults:       { _controller: WecampPlusplusBundle:Subject:add }
    methods:        [ GET ]

_createSubject:
    path:           /subject/create
    defaults:       { _controller: WecampPlusplusBundle:Subject:create }
    methods:        [ POST ]

_plusOneSubject:
    path:           /plusone
    defaults:       { _controller: WecampPlusplusBundle:Subject:plusone }
    methods:        [ POST ]

_getPlusOneSubject:
    path:           /subject/{subjectId}/plusone
    defaults:       { _controller: WecampPlusplusBundle:Subject:getPlusOnes }
    methods:        [ GET ]

_mapSubject:
    path:           /map/subject
    defaults:       { _controller: WecampPlusplusBundle:Map:displaySubject }
    methods:        [ GET ]

_download:
    pattern:        /download
    defaults:       { _controller: WecampPlusplusBundle:Download:download }
    methods:        [ GET ]